# Required Dependencies

[pkg]
cloudflared
git
gh
tar
clang
make
coreutils
openssh
python
ca-certificates
pkg-config
cmake
unzip
bash

[apt]
git
clang
make
cmake
tar
unzip

[pip]
flask
flask-auth

[npm]
