## Targets for Testing & Examples ##
##** NO QUOTATION MARKS REGARDELSS OF TYPE, they will cause y2mp3 to fail

## Sections ##
##** Must have header [targ] followed directly by the key, value url|link.
##** Additional valid key, value pairs will get added to target file metatags.
##** Valid Metatags: (artist, album, album_artist, genre, track, disc, date, composer, performer, publisher, lyrics, copyright, encoded_by, encoder, compilation, album_sort, artist_sort, title_sort) metatag 'title' just replaces 'name' functionality in y2mp3. More reliable to use 'name'.

[targ]
url = https://youtu.be/P5erThIAcQ4?is=snK7UkKkAO0XNSK9
name = Dream Catcher
artist = Whether, I

[targ]
url = https://youtu.be/L5UJPQzbN40?is=nEUMb5u-ppmT-7AS
name = Dont Let Me Fade Away
artist = Wage War

## Directs ##
##** Direct-URLs may contain trailing whitespace but no trailing in-line comments or other syntaxing.

https://youtu.be/5gxHvmUKhzk?is=U02VQWzRy2b8Bbfb