## GAMES ##
[Orna]
pkg = playorna.com.orna
alias = ['echo 'alias orna="adb shell monkey -p playorna.com.orna 1"' >> "$PREFIX/etc/bash.bashrc"', 'source "$PREFIX/etc/bash.bashrc"']

[Albion]
pkg = com.albiononline
alias = ['echo \'alias albion="adb shell monkey -p com.albiononline 1"\' >> "$PREFIX/etc/bash.bashrc"', 'source "$PREFIX/etc/bash.bashrc"']

[Ark]
pkg = com.studiowildcard.ark
alias = ['echo \'alias ark="adb shell monkey -p com.studiowildcard.ark 1"\' >> "$PREFIX/etc/bash.bashrc"', 'source "$PREFIX/etc/bash.bashrc"']

[Minecraft]
pkg = com.mojang.minecraftpe
alias = ['echo \'alias minecraft="adb shell monkey -p com.mojang.minecraftpe 1"\' >> "$PREFIX/etc/bash.bashrc"', 'source "$PREFIX/etc/bash.bashrc"']

[RISK]
pkg = com.hasbro.riskbigscreen
alias = ['echo \'alias risk="adb shell monkey -p com.hasbro.riskbigscreen 1"\' >> "$PREFIX/etc/bash.bashrc"', 'source "$PREFIX/etc/bash.bashrc"']

[AdventureCapitalist]
pkg = com.kongregate.mobile.adventurecapitalist.google
alias = ['echo \'alias advcap="adb shell monkey -p com.kongregate.mobile.adventurecapitalist.google 1"\' >> "$PREFIX/etc/bash.bashrc"', 'source "$PREFIX/etc/bash.bashrc"']

[DayR]
pkg = com.gm_shaber.dayrpremium
alias = ['echo \'alias dayr="adb shell monkey -p com.gm_shaber.dayrpremium 1"\' >> "$PREFIX/etc/bash.bashrc"', 'source "$PREFIX/etc/bash.bashrc"']

[GenshinImpact]
pkg = com.miHoYo.GenshinImpact
alias = ['echo \'alias genshin="adb shell monkey -p com.miHoYo.GenshinImpact 1"\' >> "$PREFIX/etc/bash.bashrc"', 'source "$PREFIX/etc/bash.bashrc"']

[HeroOfAethric]
pkg = com.avalon.rpg
alias = ['echo \'alias aethric="adb shell monkey -p com.avalon.rpg 1"\' >> "$PREFIX/etc/bash.bashrc"', 'source "$PREFIX/etc/bash.bashrc"']

[ShieldHeroRise]
pkg = com.ltgame.dzyzcml.global
alias = ['echo \'alias shieldhero="adb shell monkey -p com.ltgame.dzyzcml.global 1"\' >> "$PREFIX/etc/bash.bashrc"', 'source "$PREFIX/etc/bash.bashrc"']

[Twitch]
pkg = tv.twitch.android.app
alias = ['echo \'alias twitch="adb shell monkey -p tv.twitch.android.app 1"\' >> "$PREFIX/etc/bash.bashrc"', 'source "$PREFIX/etc/bash.bashrc"']

## STOCK ##
[Webull]
pkg = com.webull.stock
alias = ['echo \'alias webull="adb shell monkey -p com.webull.stock 1"\' >> "$PREFIX/etc/bash.bashrc"', 'source "$PREFIX/etc/bash.bashrc"']

[TradingView]
pkg = com.tradingview.tradingviewapp
alias = ['echo \'alias tradingview="adb shell monkey -p com.tradingview.tradingviewapp 1"\' >> "$PREFIX/etc/bash.bashrc"', 'source "$PREFIX/etc/bash.bashrc"']

[Chime]
pkg = com.onedebit.chime
alias = ['echo \'alias chime="adb shell monkey -p com.onedebit.chime 1"\' >> "$PREFIX/etc/bash.bashrc"', 'source "$PREFIX/etc/bash.bashrc"']

[Moomoo]
pkg = com.moomoo.trade
alias = ['echo \'alias moomoo="adb shell monkey -p com.moomoo.trade 1"\' >> "$PREFIX/etc/bash.bashrc"', 'source "$PREFIX/etc/bash.bashrc"']

[QuantData]
pkg = com.quantdata.app
alias = ['echo \'alias quantdata="adb shell monkey -p com.quantdata.app 1"\' >> "$PREFIX/etc/bash.bashrc"', 'source "$PREFIX/etc/bash.bashrc"']
)
## SOCIAL ##
[Facebook]
pkg = com.facebook.katana
alias = ['echo \'alias facebook="adb shell monkey -p com.facebook.katana 1"\' >> "$PREFIX/etc/bash.bashrc"', 'source "$PREFIX/etc/bash.bashrc"']

[Snapchat]
pkg = com.snapchat.android
alias = ['echo \'alias snapchat="adb shell monkey -p com.snapchat.android 1"\' >> "$PREFIX/etc/bash.bashrc"', 'source "$PREFIX/etc/bash.bashrc"']

[Discord]
pkg = com.discord
alias = ['echo \'alias discord="adb shell monkey -p com.discord 1"\' >> "$PREFIX/etc/bash.bashrc"', 'source "$PREFIX/etc/bash.bashrc"']

## AI ##
[ChatGPT]
pkg = com.openai.chatgpt
alias = ['echo \'alias chatgpt="adb shell monkey -p com.openai.chatgpt 1"\' >> "$PREFIX/etc/bash.bashrc"', 'source "$PREFIX/etc/bash.bashrc"']

[Copilot]
pkg = com.microsoft.copilot
alias = ['echo \'alias copilot="adb shell monkey -p com.microsoft.copilot 1"\' >> "$PREFIX/etc/bash.bashrc"', 'source "$PREFIX/etc/bash.bashrc"']

[Claude]
pkg = com.anthropic.claude
alias = ['echo \'alias claude="adb shell monkey -p com.anthropic.claude 1"\' >> "$PREFIX/etc/bash.bashrc"', 'source "$PREFIX/etc/bash.bashrc"']

## CODING ##
[Code]
pkg = com.ferdium.editor.code
alias = ['echo \'alias vscode="adb shell monkey -p com.ferdium.editor.code 1"\' >> "$PREFIX/etc/bash.bashrc"', 'source "$PREFIX/etc/bash.bashrc"']

[CodeEditor]
pkg = com.foxdebug.acode
alias = ['echo \'alias code="adb shell monkey -p com.foxdebug.acode 1"\' >> "$PREFIX/etc/bash.bashrc"', 'source "$PREFIX/etc/bash.bashrc"']

[RustDesk]
pkg = com.github.rustdesk
alias = ['echo \'alias rustdesk="adb shell monkey -p com.github.rustdesk 1"\' >> "$PREFIX/etc/bash.bashrc"', 'source "$PREFIX/etc/bash.bashrc"']

[ImageBB]
pkg = com.imgbb
alias = ['echo \'alias imagebb="adb shell monkey -p com.imgbb 1"\' >> "$PREFIX/etc/bash.bashrc"', 'source "$PREFIX/etc/bash.bashrc"']

[MacroDroid]
pkg = com.arlosoft.macrodroid
alias = ['echo \'alias macrodroid="adb shell monkey -p com.arlosoft.macrodroid 1"\' >> "$PREFIX/etc/bash.bashrc"', 'source "$PREFIX/etc/bash.bashrc"']

## Services ##
[FakeGPS]
pkg = com.lexa.fakegps
alias = ['echo \'alias fakegps="adb shell monkey -p com.lexa.fakegps 1"\' >> "$PREFIX/etc/bash.bashrc"', 'source "$PREFIX/etc/bash.bashrc"']

[Daylio]
pkg = net.daylio
alias = ['echo \'alias daylio="adb shell monkey -p net.daylio 1"\' >> "$PREFIX/etc/bash.bashrc"', 'source "$PREFIX/etc/bash.bashrc"']

[Spotify]
pkg = com.spotify.music
alias = ['echo \'alias spotify="adb shell monkey -p com.spotify.music 1"\' >> "$PREFIX/etc/bash.bashrc"', 'source "$PREFIX/etc/bash.bashrc"']

## Browsers ##
[Kiwi]
pkg = com.kiwibrowser.browser
alias = ['echo \'alias kiwi="adb shell monkey -p com.kiwibrowser.browser 1"\' >> "$PREFIX/etc/bash.bashrc"', 'source "$PREFIX/etc/bash.bashrc"']

[Chrome]
pkg = com.android.chrome
alias = ['echo \'alias chrome="adb shell monkey -p com.android.chrome 1"\' >> "$PREFIX/etc/bash.bashrc"', 'source "$PREFIX/etc/bash.bashrc"']

[Orbot]
pkg = org.torproject.android
alias = ['echo \'alias orbot="adb shell monkey -p org.torproject.android 1"\' >> "$PREFIX/etc/bash.bashrc"', 'source "$PREFIX/etc/bash.bashrc"']

[Orfox]
pkg = org.torproject.orfox
alias = ['echo \'alias orfox="adb shell monkey -p org.torproject.orfox 1"\' >> "$PREFIX/etc/bash.bashrc"', 'source "$PREFIX/etc/bash.bashrc"']

[TorBrowser]
pkg = org.torproject.torbrowser
alias = ['echo \'alias torbrowser="adb shell monkey -p org.torproject.torbrowser 1"\' >> "$PREFIX/etc/bash.bashrc"', 'source "$PREFIX/etc/bash.bashrc"']

[ALIAS]
echo 'alias orna="adb shell monkey -p playorna.com.orna 1"' >> "$PREFIX/etc/bash.bashrc"
echo 'alias albion="adb shell monkey -p com.albiononline 1"' >> "$PREFIX/etc/bash.bashrc"
echo 'alias ark="adb shell monkey -p com.studiowildcard.ark 1"' >> "$PREFIX/etc/bash.bashrc"
echo 'alias minecraft="adb shell monkey -p com.mojang.minecraftpe 1"' >> "$PREFIX/etc/bash.bashrc"
echo 'alias risk="adb shell monkey -p com.hasbro.riskbigscreen 1"' >> "$PREFIX/etc/bash.bashrc"
echo 'alias advcap="adb shell monkey -p com.kongregate.mobile.adventurecapitalist.google 1"' >> "$PREFIX/etc/bash.bashrc"
echo 'alias dayr="adb shell monkey -p com.gm_shaber.dayrpremium 1"' >> "$PREFIX/etc/bash.bashrc"
echo 'alias genshin="adb shell monkey -p com.miHoYo.GenshinImpact 1"' >> "$PREFIX/etc/bash.bashrc"
echo 'alias aethric="adb shell monkey -p com.avalon.rpg 1"' >> "$PREFIX/etc/bash.bashrc"
echo 'alias shieldhero="adb shell monkey -p com.ltgame.dzyzcml.global 1"' >> "$PREFIX/etc/bash.bashrc"
echo 'alias twitch="adb shell monkey -p tv.twitch.android.app 1"' >> "$PREFIX/etc/bash.bashrc"
echo 'alias webull="adb shell monkey -p com.webull.stock 1"' >> "$PREFIX/etc/bash.bashrc"
echo 'alias tradingview="adb shell monkey -p com.tradingview.tradingviewapp 1"' >> "$PREFIX/etc/bash.bashrc"
echo 'alias chime="adb shell monkey -p com.onedebit.chime 1"' >> "$PREFIX/etc/bash.bashrc"
echo 'alias moomoo="adb shell monkey -p com.moomoo.trade 1"' >> "$PREFIX/etc/bash.bashrc"
echo 'alias quantdata="adb shell monkey -p com.quantdata.app 1"' >> "$PREFIX/etc/bash.bashrc"
echo 'alias facebook="adb shell monkey -p com.facebook.katana 1"' >> "$PREFIX/etc/bash.bashrc"
echo 'alias snapchat="adb shell monkey -p com.snapchat.android 1"' >> "$PREFIX/etc/bash.bashrc"
echo 'alias discord="adb shell monkey -p com.discord 1"' >> "$PREFIX/etc/bash.bashrc"
echo 'alias chatgpt="adb shell monkey -p com.openai.chatgpt 1"' >> "$PREFIX/etc/bash.bashrc"
echo 'alias copilot="adb shell monkey -p com.microsoft.copilot 1"' >> "$PREFIX/etc/bash.bashrc"
echo 'alias claude="adb shell monkey -p com.anthropic.claude 1"' >> "$PREFIX/etc/bash.bashrc"
echo 'alias vscode="adb shell monkey -p com.ferdium.editor.code 1"' >> "$PREFIX/etc/bash.bashrc"
echo 'alias code="adb shell monkey -p com.foxdebug.acode 1"' >> "$PREFIX/etc/bash.bashrc"
echo 'alias rustdesk="adb shell monkey -p com.github.rustdesk 1"' >> "$PREFIX/etc/bash.bashrc"
echo 'alias imagebb="adb shell monkey -p com.imgbb 1"' >> "$PREFIX/etc/bash.bashrc"
echo 'alias macrodroid="adb shell monkey -p com.arlosoft.macrodroid 1"' >> "$PREFIX/etc/bash.bashrc"
echo 'alias fakegps="adb shell monkey -p com.lexa.fakegps 1"' >> "$PREFIX/etc/bash.bashrc"
echo 'alias daylio="adb shell monkey -p net.daylio 1"' >> "$PREFIX/etc/bash.bashrc"
echo 'alias spotify="adb shell monkey -p com.spotify.music 1"' >> "$PREFIX/etc/bash.bashrc"
echo 'alias kiwi="adb shell monkey -p com.kiwibrowser.browser 1"' >> "$PREFIX/etc/bash.bashrc"
echo 'alias chrome="adb shell monkey -p com.android.chrome 1"' >> "$PREFIX/etc/bash.bashrc"
echo 'alias orbot="adb shell monkey -p org.torproject.android 1"' >> "$PREFIX/etc/bash.bashrc"
echo 'alias orfox="adb shell monkey -p org.torproject.orfox 1"' >> "$PREFIX/etc/bash.bashrc"
echo 'alias torbrowser="adb shell monkey -p org.torproject.torbrowser 1"' >> "$PREFIX/etc/bash.bashrc"
source "$PREFIX/etc/bash.bashrc"

[S21 LOC]
Home = (240, 2325)
Back = (545, 2325)
Recent = (850, 2325)

[ORNA LOCS]
    [Main]
    Kingdom = (100, 2150)
    Codex = (320, 2250)
    Menu = (540, 2250)
    Items = (760, 2250)
    Explore = (975, 2150)
    Options = (975, 2300)

        [Kingdom]
        Hall = (75, 290)
        War = (230, 290)
        Raids = (390, 290)
        Gauntlet = (540, 290)
        Quests = (695, 290)
        Research = (855, 290)
        Options = (1000, 290)

            [Hall]
            Roster = (850, 2250)

            [War]
            Attack = (335, 1280)
            Defense = (740, 1280)
            Begin= (545, 1260) #Scroll-Bottom

            [Raids]
            begin = (565, 785)

            [Gauntlet]


            [Quests]


            [Research]


            [Options]


    [Codex]


    [Menu]


    [Items]


    [Explore]


    [Options]

# // Attack Screen
    [Attacking]
    Attack = (800, 1885)
    Primary = (300, 1885)
    Secondary = (300, 2060)
    Spell = (800, 2060)
    Flee = (300, 2250)
    Item = (800, 2250)
    Quick.1 = (915, 1710)
    Quick.2 = (675, 1710)
    Quick.3 = (425, 1710)
    Quick.4 = (150++-, 1710)
    Codex = ()
    Chat = ()
    Options = ()

        [Options]
        Overview = ()
        Log = ()
        Options = ()

            [Options]
            Animation.On = ()
            Animation.Faster = ()
            Animation.Off = ()
            Effects = ()
            Caster = ()
            Status.Condense = ()
            dismantle.quality = ()
            broken = ()
            poor = ()
            standard = ()
            Superior = ()

# // Shops
    [Shop]

    [Blacksmith]

    []

    [Prompts]
    Continue.bottom = (550, 2265)
    Continue.top = ()

-
